### PR TITLE
Dashboard UI

### PR DESCRIPTION
**Pull request by Franpastoragusti**
Hi Carlos, I have redesign the full UI, I hope you like it.

Let's talk for new features or improvements

Captura de pantalla 2022-10-14 a las 7 34 24

Captura de pantalla 2022-10-14 a las 7 35 58

### CODE REVIEW

**Comment by carletex** [comment]
Hey Fran, as we talked over telegram...thanks again for this!

Deployed it to https://staging-abi-ninja.surge.sh/ so the team can test it live and decide what can we do with it.

**Comment by carletex** [comment]
Hey @Franpastoragusti 

I've just created a `stage` branch which will deploy the site to `https://stage.abi.ninja` (should be ready in a few hours). That way we can test & work on it before it's ready to production.

After testing it for a bit, these are some issues (or comments) that we found:

**1.** 
image

This should disappear when network != mainnet

**2.** 
image

That spinner should go to the center of the page?

**3.** When you directly share an URL (e.g. https://abi.ninja/0x6b175474e89094c44da98b954eedeac495271d0f/mainnet), it think it'd helpful to have some message in the "blank canvas" (e.g. "Add methods from the sidebar....")

image

**4.** Current abi.ninja has a way to share URL with the selected methods (e.g. https://abi.ninja/0x6b175474e89094c44da98b954eedeac495271d0f/mainnet?functions=balanceOf%2Cdeny). Clicking the gear icon:

image

In the new version, we could do the same but directly when adding / removing items from the sidebar.

**5.** Let's hide the result if empty
image

**6.** We weren't sure about this: A way to remove a "method card" inside the card itself (instead of having to go to the sidebar)


**7.** It's not usable on mobile (no way to add/remove methods from the sidebar)

**8.** We don't need the network selection when you already on a contract: 
image

Maybe have the connect button there?

**9.** Can we increase the font-size a bit here?
image

Thanks for this!!

**Comment by Franpastoragusti** [comment]
Hi @carletex sorry but i have not see the comments and the email, here are all the changes let me know how do you feel it

**Comment by carletex** [comment]
Hey @Franpastoragusti This is great, thanks! :)

The only (minor) thing: If you check the react console (where you run `yarn start`) you'll see a lot of warnings:

image

You can configure eslint & prettier in your IDE to fix almost all this automagically (on save). You can check .prettierrc on packages/react-app/


image
I fixed all the prettier issues and some more important linting issues (like no using async on useEffects)

image

Pushing to stage so we can test there.

**Pull request merged**
